services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379


